### ISSUE TITLE
Have a separate field for route/name 

### ISSUE THREAD

**Issue by tony56a** [PropaneDragon/RoadNamer#4]
This is primarily for cimtographer integration, but since OSM ways define separate name(road name), and reference(for roads, seems like the [route designation](http://wiki.openstreetmap.org/wiki/Relation:route#Tags)) tags, it might be useful to allow users to define these values separately, especially for cases when they want to overlay a route name on top of multiple physical road segments (see: [Downtown Connector](https://en.wikipedia.org/wiki/Downtown_Connector), [Conestoga Parkway](https://en.wikipedia.org/wiki/Conestoga_Parkway)).

**Comment by PropaneDragon** [comment]
Thanks Tony. I'll have a look at it as soon as I can :)

**Comment by tony56a** [comment]
Superseded by MarkARoute
