### ISSUE TITLE
Pre- and Postfixes without space separator

### ISSUE THREAD

**Issue by boformer** [PropaneDragon/RoadNamer#6]
German road names often look like this:

```
Josephinenstraße
Bergstraße
Ahornweg
Rotkelchenweg
```

The postfix ("-straße", "-weg", "-allee", "-ring") is not separated. There should be a way to declare if a postfix is separated by a space. 

Problem with prefixes: The first letter of the actual name has to be converted to lowercase.

Of course there are also combinations where a space before the prefix/postfix is required:

```
Berliner Straße
Große Heide
```

For now I will just include the postfix in the name.

German road names are usually a single word.

**Comment by PropaneDragon** [comment]
Ah of course. Don't know how I missed this, but I'll add some new tags.

**Comment by PropaneDragon** [comment]
Just remembered this is still open. I've fixed this now with two new tags.
